import { _BaseSingleColService } from 'ag-grid-community';
import type { AgColumn, BeanCollection, CellCtrl, CellPosition, CellRange, ColDef, ColKind, IRowNumbersRowResizeFeature, IRowNumbersService, NamedBean, PropertyValueChangedEvent, _HeaderComp } from 'ag-grid-community';
import type { RangeSelectionExtension } from '../rangeSelection/rangeSelectionExtensions';
export declare class RowNumbersService extends _BaseSingleColService implements NamedBean, IRowNumbersService, RangeSelectionExtension {
    beanName: "rowNumbersSvc";
    protected readonly colKind: ColKind;
    private rangeSvc?;
    private ariaAnnounce;
    private visibleCols;
    wireBeans(beans: BeanCollection): void;
    private isIntegratedWithSelection;
    private isSuppressCellSelectionIntegration;
    private rowNumberOverrides;
    private lastColumnResized;
    private readonly boundValueGetter;
    private readonly boundCellClass;
    postConstruct(): void;
    shouldSkipColumn(column: AgColumn): boolean;
    isAllColumnsSelectionCell(cellPosition: CellPosition): boolean;
    isAllColumnsRange(range: CellRange, allColumns: AgColumn[]): boolean;
    private registerRangeSelectionExtension;
    isEnabled(): boolean;
    handleMouseDownOnCell(cellPosition: CellPosition, mouseEvent: MouseEvent): boolean;
    handleKeyDownOnCell(cellPosition: CellPosition, event: KeyboardEvent): boolean;
    private selectRowCells;
    updateColumns(event: PropertyValueChangedEvent<any>): void;
    destroy(): void;
    setupForHeader(comp: _HeaderComp): void;
    private onGridCellFocused;
    createRowNumbersRowResizerFeature(ctrl: CellCtrl): IRowNumbersRowResizeFeature | undefined;
    private refreshSelectionIntegration;
    private refreshRowNumberOverrides;
    private onHeaderFocus;
    private onHeaderKeyDown;
    private onHeaderClick;
    private selectAllCellsFromHeader;
    private focusAllCellsFromHeaderClick;
    private refreshCells;
    private createDummyElement;
    protected createColDef(): ColDef;
    private valueGetter;
    private getHeaderClass;
    private getCellClass;
    private focusFirstRenderedCellAtRowPosition;
}
