declare const _default: {
    IF: ({ values }: import("packages/ag-grid-community/dist/types/src/main-umd-noStyles").FormulaFunctionParams) => unknown;
    NOW: () => Date;
    TODAY: () => Date;
    PRODUCT: ({ values }: import("packages/ag-grid-community/dist/types/src/main-umd-noStyles").FormulaFunctionParams) => number | bigint;
    SUM: ({ values }: import("packages/ag-grid-community/dist/types/src/main-umd-noStyles").FormulaFunctionParams) => number | Date | bigint;
    ADD: ({ values }: import("packages/ag-grid-community/dist/types/src/main-umd-noStyles").FormulaFunctionParams) => number | Date | bigint;
    SUMIF: ({ args }: import("packages/ag-grid-community/dist/types/src/main-umd-noStyles").FormulaFunctionParams) => number | bigint;
    POWER: ({ values }: import("packages/ag-grid-community/dist/types/src/main-umd-noStyles").FormulaFunctionParams) => number;
    MIN: ({ values }: import("packages/ag-grid-community/dist/types/src/main-umd-noStyles").FormulaFunctionParams) => any;
    MAX: ({ values }: import("packages/ag-grid-community/dist/types/src/main-umd-noStyles").FormulaFunctionParams) => any;
    AVERAGE: ({ values }: import("packages/ag-grid-community/dist/types/src/main-umd-noStyles").FormulaFunctionParams) => number | Date;
    MEDIAN: ({ values }: import("packages/ag-grid-community/dist/types/src/main-umd-noStyles").FormulaFunctionParams) => number | Date;
    ROUND: ({ values }: import("packages/ag-grid-community/dist/types/src/main-umd-noStyles").FormulaFunctionParams) => number;
    COUNT: ({ values }: import("packages/ag-grid-community/dist/types/src/main-umd-noStyles").FormulaFunctionParams) => number;
    COUNTA: ({ values }: import("packages/ag-grid-community/dist/types/src/main-umd-noStyles").FormulaFunctionParams) => number;
    COUNTBLANK: ({ values }: import("packages/ag-grid-community/dist/types/src/main-umd-noStyles").FormulaFunctionParams) => number;
    COUNTIF: ({ args }: import("packages/ag-grid-community/dist/types/src/main-umd-noStyles").FormulaFunctionParams) => number;
    RAND: () => number;
    CONCAT: ({ values }: import("packages/ag-grid-community/dist/types/src/main-umd-noStyles").FormulaFunctionParams) => string;
    CONCATENATE: ({ values }: import("packages/ag-grid-community/dist/types/src/main-umd-noStyles").FormulaFunctionParams) => string;
    '+': ({ values }: import("packages/ag-grid-community/dist/types/src/main-umd-noStyles").FormulaFunctionParams) => number | Date | bigint;
    '-': ({ values }: import("packages/ag-grid-community/dist/types/src/main-umd-noStyles").FormulaFunctionParams) => number | Date | bigint;
    '*': ({ values }: import("packages/ag-grid-community/dist/types/src/main-umd-noStyles").FormulaFunctionParams) => number | bigint;
    '/': ({ values }: import("packages/ag-grid-community/dist/types/src/main-umd-noStyles").FormulaFunctionParams) => number;
    '^': ({ values }: import("packages/ag-grid-community/dist/types/src/main-umd-noStyles").FormulaFunctionParams) => number;
    '%': ({ values }: import("packages/ag-grid-community/dist/types/src/main-umd-noStyles").FormulaFunctionParams) => number;
    '=': ({ values }: import("packages/ag-grid-community/dist/types/src/main-umd-noStyles").FormulaFunctionParams) => boolean;
    '&': ({ values }: import("packages/ag-grid-community/dist/types/src/main-umd-noStyles").FormulaFunctionParams) => string;
    '<>': ({ values }: import("packages/ag-grid-community/dist/types/src/main-umd-noStyles").FormulaFunctionParams) => boolean;
    '>': ({ values }: import("packages/ag-grid-community/dist/types/src/main-umd-noStyles").FormulaFunctionParams) => boolean;
    '>=': ({ values }: import("packages/ag-grid-community/dist/types/src/main-umd-noStyles").FormulaFunctionParams) => boolean;
    '<': ({ values }: import("packages/ag-grid-community/dist/types/src/main-umd-noStyles").FormulaFunctionParams) => boolean;
    '<=': ({ values }: import("packages/ag-grid-community/dist/types/src/main-umd-noStyles").FormulaFunctionParams) => boolean;
};
export default _default;
